delete from dentalrj.DentalInsurance;
INSERT INTO dentalrj.DentalInsurance
(Id, CreatedAt, CreatedBy, Name, BrandName, NeedAuthorization, HasReimbursement, CopaymentPercentage, Status ) values 
(UUID(), now(), 'Loader', 'PARTICULAR', 'PARTICULAR',0, 0, 0, 1),
(UUID(), now(), 'Loader', 'AMIL DENTAL', 'AMIL DENTAL',0, 0, 0, 1),
(UUID(), now(), 'Loader', 'CAPESESP', 'CAPESESP',0, 1, 0, 1),
(UUID(), now(), 'Loader', 'HAPVIDA', 'HAPVIDA',0, 0, 0, 1),
(UUID(), now(), 'Loader', 'INPAO DENTAL', 'INPAO DENTAL',0, 0, 0, 1),
(UUID(), now(), 'Loader', 'INTERODONTO', 'INTERODONTO (NOTREDAME INTERMEDICA)',0, 0, 0, 1),
(UUID(), now(), 'Loader', 'LIFE EMPRESARIAL', 'LIFE EMPRESARIAL',0, 0, 0, 1),
(UUID(), now(), 'Loader', 'MEDISERVICE', 'MEDISERVICE',0, 0, 0, 1),
(UUID(), now(), 'Loader', 'METLIFE', 'METLIFE',0, 0, 0, 1),
(UUID(), now(), 'Loader', 'ODONTO EMPRESAS', 'ODONTO EMPRESAS',0, 0, 0, 1),
(UUID(), now(), 'Loader', 'PORTO SEGURO', 'PORTO SEGURO',0, 0, 0, 1),
(UUID(), now(), 'Loader', 'PRIMAVIDA', 'PRIMAVIDA',0, 0, 0, 1),
(UUID(), now(), 'Loader', 'REAL GRANDEZA / FURNAS', 'REAL GRANDEZA',0, 1, 0, 1),
(UUID(), now(), 'Loader', 'SORRISO ASSIST', 'SORRISO ASSIST',0, 0, 0, 1),
(UUID(), now(), 'Loader', 'SULAMERICA DENTAL', 'SULAMERICA DENTAL',0, 0, 0, 1),
(UUID(), now(), 'Loader', 'UNIMED DENTAL / UNIMED ODONTO', 'UNIMED ODONTO',0, 0, 0, 1),
(UUID(), now(), 'Loader', 'SEMPRE ODONTO', 'SEMPRE ODONTO',0, 1, 0, 0),
(UUID(), now(), 'Loader', 'DIX DENTAL (AMIL DENTAL)', 'DIX DENTAL',0, 0, 0, 0),
(UUID(), now(), 'Loader', 'MEDIAL DENTAL (AMIL DENTAL)', 'MEDIAL DENTAL',0, 0, 0, 1),
(UUID(), now(), 'Loader', 'REDE BRAZIL DENTAL', 'REDE BRAZIL DENTAL',0, 0, 0, 1),
(UUID(), now(), 'Loader', 'BRADESCO (REEMBOLSO)', '',0, 0, 0, 0),
(UUID(), now(), 'Loader', 'ODONTOPREV (REEMBOLSO)', '',0, 0, 0, 0),
(UUID(), now(), 'Loader', 'BELO DENTE', 'BELO DENTE',0, 0, 0, 1),
(UUID(), now(), 'Loader', 'DENTAL CENTER (AMIL DENTAL)', 'DENTAL CENTER',0, 0, 0, 0),
(UUID(), now(), 'Loader', 'VITAL', '',0, 0, 0, 0),
(UUID(), now(), 'Loader', 'LINCX', 'LINCX',0, 1, 0, 1),
(UUID(), now(), 'Loader', 'GOLDEN DENTAL (GOLDENTAL)', 'GOLDEN CROSS (GOLDENTAL)',0, 0, 0, 1),
(UUID(), now(), 'Loader', 'IBEROSTAR', '',0, 0, 0, 0),
(UUID(), now(), 'Loader', 'CEDOM', 'CEDOM',0, 0, 0, 0),
(UUID(), now(), 'Loader', 'ALL LAB', '',0, 0, 0, 0),
(UUID(), now(), 'Loader', 'ASSIM / DENTSIM', 'ASSIM / DENTSIM',0, 0, 0, 1),
(UUID(), now(), 'Loader', 'BRADESCO DENTAL', 'BRADESCO DENTAL',0, 1, 0, 1),
(UUID(), now(), 'Loader', 'ODONTOPREV', 'ODONTOPREV',0, 1, 0, 1),
(UUID(), now(), 'Loader', 'POSTAL ODONTO CORREIOS (SAO FRANCISCO)', 'POSTAL ODONTO CORREIOS',0, 0, 0, 1),
(UUID(), now(), 'Loader', 'CAURJ (BELO DENTE)', 'CAURJ',0, 0, 0, 0),
(UUID(), now(), 'Loader', 'CABERJ (METLIFE)', 'CABERJ',0, 0, 0, 1),
(UUID(), now(), 'Loader', 'ODONTO FIT (LIFE EMPRESARIAL)', 'ODONTO FIT',0, 0, 0, 1),
(UUID(), now(), 'Loader', 'ITAU ODONTO (METLIFE)', 'ITAU ODONTO',0, 0, 0, 1),
(UUID(), now(), 'Loader', 'BV DENTAL (METLIFE)', 'BV DENTAL',0, 0, 0, 1),
(UUID(), now(), 'Loader', 'AES ERGOS DENTAL (METLIFE)', 'AES ERGOS DENTAL',0, 0, 0, 1),
(UUID(), now(), 'Loader', 'BB DENTAL (ODONTOPREV)', 'BB DENTAL',0, 1, 0, 1),
(UUID(), now(), 'Loader', 'DENTAL CORP (ODONTOPREV)', 'DENTAL CORP',0, 1, 0, 1),
(UUID(), now(), 'Loader', 'IBI ODONTO C&A (ODONTOPREV)', 'IBI ODONTO C&A',0, 1, 0, 1),
(UUID(), now(), 'Loader', 'ODONTO SERV (ODONTOPREV)', 'ODONTO SERV',0, 1, 0, 1),
(UUID(), now(), 'Loader', 'ODONTOSISTEM (ODONTOPREV)', 'ODONTOSISTEM',0, 1, 0, 1),
(UUID(), now(), 'Loader', 'PRIVIAN (ODONTOPREV)', 'PRIVIAN',0, 0, 0, 1),
(UUID(), now(), 'Loader', 'PRONTODENTE (ODONTOPREV)', 'PRONTODENTE',0, 1, 0, 1),
(UUID(), now(), 'Loader', 'RIACHUELO ODONTO MIDWAY (ODONTOPREV)', 'RIACHUELO ODONTO MIDWAY',0, 1, 0, 1),
(UUID(), now(), 'Loader', 'REDE DENTAL (ODONTOPREV)', 'REDE DENTAL',0, 1, 0, 1),
(UUID(), now(), 'Loader', 'SEPAO (ODONTOPREV)', 'SEPAO',0, 1, 0, 1),
(UUID(), now(), 'Loader', 'BANESTES ODONTO (REDE BRAZIL DENTAL)', 'BANESTES ODONTO',0, 0, 0, 1),
(UUID(), now(), 'Loader', 'BIORAL (REDE BRAZIL DENTAL)', 'BIORAL',0, 0, 0, 1),
(UUID(), now(), 'Loader', 'DENTALSEG (REDE BRAZIL DENTAL)', 'DENTALSEG',0, 0, 0, 1),
(UUID(), now(), 'Loader', 'GEAP', 'GEAP',0, 0, 0, 1),
(UUID(), now(), 'Loader', 'GREEN ODONTO (REDE BRAZIL DENTAL)', 'GREEN ODONTO',0, 0, 0, 1),
(UUID(), now(), 'Loader', 'LIS DENTAL (REDE BRAZIL DENTAL)', 'LIS DENTAL',0, 0, 0, 1),
(UUID(), now(), 'Loader', 'MARISA ODONTO (REDE BRAZIL DENTAL)', 'MARISA ODONTO',0, 0, 0, 1),
(UUID(), now(), 'Loader', 'PAN DENTAL (REDE BRAZIL DENTAL)', 'PAN DENTAL',0, 0, 0, 1),
(UUID(), now(), 'Loader', 'PREVIDENT (REDE BRAZIL DENTAL)', 'PREVIDENT',0, 0, 0, 1),
(UUID(), now(), 'Loader', 'PRODENT', 'PRODENT ',0, 0, 0, 1),
(UUID(), now(), 'Loader', 'SANTANDER ODONTO', 'SANTANDER ODONTO',0, 0, 0, 1),
(UUID(), now(), 'Loader', 'CARREFOUR DENTAL (ODONTO EMPRESAS)', 'CARREFOUR DENTAL',0, 0, 0, 1),
(UUID(), now(), 'Loader', 'DENTAL LIGHT LEADER (ODONTO EMPRESAS)', 'DENTAL LIGHT LEADER',0, 0, 0, 1),
(UUID(), now(), 'Loader', 'TEMPO DENTAL (ODONTO EMPRESAS)', 'TEMPO DENTAL',0, 0, 0, 1),
(UUID(), now(), 'Loader', 'CAIXA SEGURADORA (ODONTO EMPRESAS)', 'CAIXA SEGURADORA',0, 0, 0, 1),
(UUID(), now(), 'Loader', 'ODONTO MAXX (ODONTO EMPRESAS)', 'ODONTO MAXX',0, 0, 0, 1),
(UUID(), now(), 'Loader', 'DENTAL PREMIADO (ODONTO EMPRESAS)', 'DENTAL PREMIADO',0, 0, 0, 1),
(UUID(), now(), 'Loader', 'ODONTO TOTAL (ODONTO EMPRESAS)', 'ODONTO TOTAL',0, 0, 0, 1),
(UUID(), now(), 'Loader', 'ODONTO FAMILIA (ODONTO EMPRESAS)', 'ODONTO FAMILIA',0, 0, 0, 1),
(UUID(), now(), 'Loader', 'LEOLAR ODONTO (ODONTO EMPRESAS)', 'LEOLAR ODONTO',0, 0, 0, 1),
(UUID(), now(), 'Loader', 'DENTAL SIMPLES (ODONTO EMPRESAS)', 'DENTAL SIMPLES',0, 0, 0, 1),
(UUID(), now(), 'Loader', 'CREDICARD ODONTO (ODONTO EMPRESAS)', 'CREDICARD ODONTO',0, 0, 0, 1),
(UUID(), now(), 'Loader', 'SENFF ODONTO (ODONTO EMPRESAS)', 'SENFF ODONTO',0, 0, 0, 1),
(UUID(), now(), 'Loader', 'TO GARANTIDO (ODONTO EMPRESAS)', 'TO GARANTIDO',0, 0, 0, 1),
(UUID(), now(), 'Loader', 'FAMILIA SORRISO NALIN (SEMPRE ODONTO)', 'FAMILIA SORRISO NALIN',0, 1, 0, 1),
(UUID(), now(), 'Loader', 'SORRISO FAMILIA (SEMPRE ODONTO)', 'SORRISO FAMILIA',0, 1, 0, 1),
(UUID(), now(), 'Loader', 'CAEDU ODONTO (SEMPRE ODONTO)', 'CAEDU ODONTO',0, 1, 0, 1),
(UUID(), now(), 'Loader', 'DI SANTINNI ODONTO (SEMPRE ODONTO)', 'DI SANTINNI ODONTO',0, 1, 0, 1),
(UUID(), now(), 'Loader', 'SERVIR ODONTO (SEMPRE ODONTO)', 'SERVIR ODONTO',0, 1, 0, 1),
(UUID(), now(), 'Loader', 'CONFIANÇA ODONTO (SEMPRE ODONTO)', 'CONFIANÇA ODONTO',0, 1, 0, 1),
(UUID(), now(), 'Loader', 'SAO FRANCISCO', 'SAO FRANCISCO',0, 0, 0, 1),
(UUID(), now(), 'Loader', 'MAPFRE ODONTO (REDE BRAZIL DENTAL)', 'MAPFRE ODONTO',0, 0, 0, 1),
(UUID(), now(), 'Loader', 'DENTAL UNI (ODONTOLIFE)', 'DENTAL UNI',0, 0, 0, 1),
(UUID(), now(), 'Loader', 'ODONTOLIFE', 'ODONTOLIFE',0, 0, 0, 1),
(UUID(), now(), 'Loader', 'SOLIDENTE (SORRISO ASSIST)', 'SOLIDENTE',0, 0, 0, 1),
(UUID(), now(), 'Loader', 'BEM+ODONTO (SORRISO ASSIST)', 'BEM+ODONTO',0, 0, 0, 1),
(UUID(), now(), 'Loader', 'MAISDENTAL.COM', 'MAIS DENTAL',0, 0, 0, 1),
(UUID(), now(), 'Loader', 'W.DENTAL (REDE BRAZIL DENTAL)', 'W DENTAL',0, 0, 0, 1),
(UUID(), now(), 'Loader', 'CARE PLUS', 'CARE PLUS',0, 0, 0, 1),
(UUID(), now(), 'Loader', 'PERNAMBUCANAS (REDE BRAZIL DENTAL)', 'PERNAMBUCANAS ODONTO',0, 0, 0, 1),
(UUID(), now(), 'Loader', 'ODONTOBASE', 'ODONTOBASE',1, 1, 0, 1),
(UUID(), now(), 'Loader', 'BANCO INTER ODONTO (METLIFE)', 'BANCO INTER ODONTO',0, 0, 0, 1),
(UUID(), now(), 'Loader', 'HUMANA ODONTO', 'HUMANA ODONTO',1, 0, 0, 1),
(UUID(), now(), 'Loader', 'SAMP', 'SAMP',1, 0, 0, 1),
(UUID(), now(), 'Loader', 'ABERTTA SAÚDE', 'ABERTTA SAÚDE',0, 1, 0, 1),
(UUID(), now(), 'Loader', 'AESP ODONTO', 'AESP ODONTO',0, 1, 0, 1),
(UUID(), now(), 'Loader', 'AFFEMG', 'AFFEMG',0, 1, 0, 1),
(UUID(), now(), 'Loader', 'AFRESP', 'AFRESP',0, 1, 0, 1),
(UUID(), now(), 'Loader', 'ANFIP', 'ANFIP',0, 1, 0, 1),
(UUID(), now(), 'Loader', 'APAS', 'APAS',0, 1, 0, 1),
(UUID(), now(), 'Loader', 'ARM ODONTO', 'ARM ODONTO',0, 1, 0, 1),
(UUID(), now(), 'Loader', 'ASSEFAZ', 'ASSEFAZ',0, 1, 0, 1),
(UUID(), now(), 'Loader', 'ASTRA S/A', 'ASTRA S/A',0, 1, 0, 1),
(UUID(), now(), 'Loader', 'AVAMP', 'AVAMP',0, 1, 0, 1),
(UUID(), now(), 'Loader', 'BARDELLA', 'BARDELLA',0, 1, 0, 1),
(UUID(), now(), 'Loader', 'BNDES (FAPES)', 'FAPES (BNDES)',0, 1, 0, 1),
(UUID(), now(), 'Loader', 'BRF', 'BRF',0, 1, 0, 1),
(UUID(), now(), 'Loader', 'CABESP', 'CABESP',0, 1, 0, 1),
(UUID(), now(), 'Loader', 'CAMARJ', 'CAMARJ',0, 1, 0, 1),
(UUID(), now(), 'Loader', 'CASEC', 'CASEC',0, 1, 0, 1),
(UUID(), now(), 'Loader', 'CASEMBRAPA', 'CASEMBRAPA',0, 1, 0, 1),
(UUID(), now(), 'Loader', 'CASSI', 'CASSI',0, 1, 0, 1),
(UUID(), now(), 'Loader', 'CAURJ', 'CAURJ',0, 1, 0, 1),
(UUID(), now(), 'Loader', 'CEDAE', 'CEDAE',0, 1, 0, 1),
(UUID(), now(), 'Loader', 'CEMIG SAÚDE', 'CEMIG SAÚDE',0, 1, 0, 1),
(UUID(), now(), 'Loader', 'CEORP', 'CEORP',0, 1, 0, 1),
(UUID(), now(), 'Loader', 'CETESB', 'CETESB',0, 1, 0, 1),
(UUID(), now(), 'Loader', 'CETSP', 'CETSP',0, 1, 0, 1),
(UUID(), now(), 'Loader', 'CONAB', 'CONAB',0, 1, 0, 1),
(UUID(), now(), 'Loader', 'COPASS', 'COPASS',0, 1, 0, 1),
(UUID(), now(), 'Loader', 'CORP DENTAL', 'CORP DENTAL',0, 1, 0, 1),
(UUID(), now(), 'Loader', 'CROWN ODONTO', 'CROWN ODONTO',0, 1, 0, 1),
(UUID(), now(), 'Loader', 'DENT SYSTEM', 'DENT SYSTEM',0, 1, 0, 1),
(UUID(), now(), 'Loader', 'DENTAL PLUS', 'DENTAL PLUS',0, 1, 0, 1),
(UUID(), now(), 'Loader', 'DENTALPAR', 'DENTALPAR',0, 1, 0, 0),
(UUID(), now(), 'Loader', 'DENTALVIDAS', 'DENTALVIDAS',0, 1, 0, 1),
(UUID(), now(), 'Loader', 'ECONOMUS', 'ECONOMUS',0, 1, 0, 1),
(UUID(), now(), 'Loader', 'ELETROBRAS', 'ELETROBRAS',0, 1, 0, 1),
(UUID(), now(), 'Loader', 'ELETRONUCLEAR', 'ELETRONUCLEAR',0, 1, 0, 1),
(UUID(), now(), 'Loader', 'ELETROS SAÚDE', 'ELETROS SAÚDE',0, 1, 0, 1),
(UUID(), now(), 'Loader', 'EVIDA', 'EVIDA',0, 1, 0, 1),
(UUID(), now(), 'Loader', 'FACEB', 'FACEB',0, 1, 0, 1),
(UUID(), now(), 'Loader', 'FIOSAÚDE', 'FIOSAÚDE',0, 1, 0, 1),
(UUID(), now(), 'Loader', 'FUNDAÇÃO COPEL', 'FUNDAÇÃO COPEL',0, 1, 0, 1),
(UUID(), now(), 'Loader', 'FUNDAÇÃO FIAT', 'FUNDAÇÃO FIAT',0, 1, 0, 1),
(UUID(), now(), 'Loader', 'FUNDACAO LEONOR DE BARROS CAMARGO', 'FUNDACAO LEONOR DE BARROS CAMARGO',0, 1, 0, 1),
(UUID(), now(), 'Loader', 'FUNDAÇÃO SÃO FRANCISCO XAVIER', 'FUNDAÇÃO SÃO FRANCISCO XAVIER',0, 1, 0, 1),
(UUID(), now(), 'Loader', 'FURNAS', 'FURNAS',0, 1, 0, 1),
(UUID(), now(), 'Loader', 'HB SAÚDE', 'HB SAÚDE',0, 1, 0, 1),
(UUID(), now(), 'Loader', 'ICS', 'ICS',0, 1, 0, 1),
(UUID(), now(), 'Loader', 'INTEGRAL DENTAL', 'INTEGRAL DENTAL',0, 1, 0, 1),
(UUID(), now(), 'Loader', 'ISODONT', 'ISODONT',0, 1, 0, 1),
(UUID(), now(), 'Loader', 'MAIS SAÚDE', 'MAIS SAÚDE',0, 1, 0, 1),
(UUID(), now(), 'Loader', 'METRUS', 'METRUS',0, 1, 0, 1),
(UUID(), now(), 'Loader', 'MOGIDONTO', 'MOGIDONTO',0, 1, 0, 1),
(UUID(), now(), 'Loader', 'MULTI - BUCAL', 'MULTI - BUCAL',0, 1, 0, 1),
(UUID(), now(), 'Loader', 'NUCLEP', 'NUCLEP',0, 1, 0, 1),
(UUID(), now(), 'Loader', 'ODONTO SEG', 'REDE BRAZIL DENTAL',0, 0, 0, 1),
(UUID(), now(), 'Loader', 'ODONTOART', 'ODONTOART',0, 1, 0, 1),
(UUID(), now(), 'Loader', 'ODONTOCLÍNICA', 'ODONTOCLÍNICA',0, 1, 0, 1),
(UUID(), now(), 'Loader', 'ODONTOGROUP', 'ODONTOGROUP',0, 1, 0, 1),
(UUID(), now(), 'Loader', 'ODONTOLIVE', 'ODONTOLIVE',0, 1, 0, 1),
(UUID(), now(), 'Loader', 'OMINT', 'OMINT',0, 1, 0, 1),
(UUID(), now(), 'Loader', 'ORAL SAÚDE', 'ORAL SAÚDE',0, 1, 0, 1),
(UUID(), now(), 'Loader', 'ORION ODONTO', 'ORION ODONTO',0, 1, 0, 1),
(UUID(), now(), 'Loader', 'ORTOCLIN', 'ORTOCLIN',0, 1, 0, 1),
(UUID(), now(), 'Loader', 'PASA', 'PASA',0, 1, 0, 1),
(UUID(), now(), 'Loader', 'PETROBRAS APS', 'PETROBRAS APS',0, 1, 0, 1),
(UUID(), now(), 'Loader', 'PLENA SAÚDE', 'PLENA SAÚDE',0, 1, 0, 1),
(UUID(), now(), 'Loader', 'PLENODONTO', 'PLENODONTO',0, 1, 0, 1),
(UUID(), now(), 'Loader', 'PROASA', 'PROASA',0, 1, 0, 1),
(UUID(), now(), 'Loader', 'S P A SAUDE', 'S P A SAUDE',0, 1, 0, 1),
(UUID(), now(), 'Loader', 'SÃO CRISTÓVÃO SAÚDE', 'SÃO CRISTÓVÃO SAÚDE',0, 1, 0, 1),
(UUID(), now(), 'Loader', 'SÃO LUCAS SAÚDE', 'SÃO LUCAS SAÚDE',0, 1, 0, 1),
(UUID(), now(), 'Loader', 'SAÚDE BRB', 'SAÚDE BRB',0, 1, 0, 1),
(UUID(), now(), 'Loader', 'SAÚDE CAIXA', 'SAÚDE CAIXA',0, 1, 0, 1),
(UUID(), now(), 'Loader', 'SAÚDE SIM', 'SAÚDE SIM',0, 1, 0, 1),
(UUID(), now(), 'Loader', 'SEPACO', 'SEPACO',0, 1, 0, 1),
(UUID(), now(), 'Loader', 'SERMED ODONTO', 'SERMED ODONTO',0, 1, 0, 1),
(UUID(), now(), 'Loader', 'SERPRO', 'SERPRO',0, 1, 0, 1),
(UUID(), now(), 'Loader', 'SICARD', 'SICARD',0, 1, 0, 1),
(UUID(), now(), 'Loader', 'SINDIFISCO', 'SINDIFISCO',0, 1, 0, 1),
(UUID(), now(), 'Loader', 'SORRIDEN', 'SORRIDEN',0, 1, 0, 1),
(UUID(), now(), 'Loader', 'SORRISO UNIDENT', 'SORRISO UNIDENT',0, 1, 0, 1),
(UUID(), now(), 'Loader', 'TOP DOCTORS', 'TOP DOCTORS',0, 1, 0, 1),
(UUID(), now(), 'Loader', 'UNIMED BELO HORIZONTE', 'UNIMED BELO HORIZONTE',0, 1, 0, 1),
(UUID(), now(), 'Loader', 'UNIMED-RIO DENTAL', 'UNIMED RIO DENTAL',0, 0, 0, 0),
(UUID(), now(), 'Loader', 'UNIODONTO', 'UNIODONTO',0, 1, 0, 1),
(UUID(), now(), 'Loader', 'UNISAUDEMS', 'UNISAUDEMS',0, 1, 0, 1),
(UUID(), now(), 'Loader', 'UNIVERSAL DENTAL', 'UNIVERSAL DENTAL',0, 1, 0, 1),
(UUID(), now(), 'Loader', 'VALE', 'VALE',0, 1, 0, 1),
(UUID(), now(), 'Loader', 'VIP PLANOS', 'VIP PLANOS',0, 1, 0, 1),
(UUID(), now(), 'Loader', 'VIVEST (FUNDAÇÃO CESP)', 'VIVEST (FUNDAÇÃO CESP)',0, 1, 0, 1),
(UUID(), now(), 'Loader', 'REDE UNNA', 'REDE UNNA',0, 1, 0, 1),
(UUID(), now(), 'Loader', 'ODONTO SIGMA', 'ODONTO SIGMA',0, 0, 0, 1),
(UUID(), now(), 'Loader', 'UFERJ', 'UFERJ',0, 0, 0, 1),
(UUID(), now(), 'Loader', 'AMIL DO SEU JEITO', 'AMIL DO SEU JEITO',0, 0, 0, 1),
(UUID(), now(), 'Loader', 'Petrobras (RHMed)', 'Petrobras (RHMed)',0, 0, 0, 1);