INSERT INTO dentalrj.Dentistry (Id, Status, CreatedAt, CreatedBy, Name) values 
	(UUID(), 1, now(), 'Loader', 'ORTODONTIA'),
	(UUID(), 1, now(), 'Loader', 'PROTESE'),
	(UUID(), 1, now(), 'Loader', 'CLINICO GERAL'),
	(UUID(), 1, now(), 'Loader', 'IMPLANTODONTIA'),
	(UUID(), 1, now(), 'Loader', 'ENDODONTIA'),
	(UUID(), 1, now(), 'Loader', '1 VEZ E LIMPEZA'),
	(UUID(), 1, now(), 'Loader', 'CIRURGIA'),
	(UUID(), 1, now(), 'Loader', 'ODONTOPEDIATRIA'),
	(UUID(), 1, now(), 'Loader', 'PERIODONTIA'),
	(UUID(), 1, now(), 'Loader', 'DENTISTICA'),
	(UUID(), 1, now(), 'Loader', 'DIAGNOSTICO'),
	(UUID(), 1, now(), 'Loader', 'DTM'),
	(UUID(), 1, now(), 'Loader', 'PACIENTES ESPECIAIS'),
	(UUID(), 1, now(), 'Loader', 'PREVENCAO'),
	(UUID(), 1, now(), 'Loader', 'RADIOLOGIA'),
	(UUID(), 1, now(), 'Loader', 'URGENCIA'),
	(UUID(), 1, now(), 'Loader', 'CLAREAMENTO'),
	(UUID(), 1, now(), 'Loader', 'CONSULTA'),
	(UUID(), 1, now(), 'Loader', 'BOTOX E PREENCHIMENTO '),
	(UUID(), 1, now(), 'Loader', 'ALINHADORES TRANSPARENTES');